package entidad;
// Generated 26/01/2018 12:02:55 PM by Hibernate Tools 4.3.1



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idRol;
     private String nombreRol;

    public Rol() {
    }

    public Rol(int idRol, String nombreRol) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }




}


